### ISSUE TITLE
Target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/q-municate-services-ios#132]
I am creating my private pod based on q-municate-services-ios and I am getting following error when I run the following command.

`pod lib lint --verbose`

<img width="941" alt="screen shot 2016-02-16 at 6 55 54 pm" src="https://cloud.githubusercontent.com/assets/204423/13078031/74c98880-d4de-11e5-9ec9-0729976c3cd8.png">

**Comment by iSevenDays** [comment]
Hi itsaboutcode,

It is usually means that you have !use_frameworks in your podfile

Please see

https://github.com/QuickBlox/q-municate-services-ios/issues/119
https://github.com/QuickBlox/q-municate-services-ios/issues/111
https://github.com/QuickBlox/q-municate-services-ios/issues/98

Thanks!

**Comment by itsaboutcode** [comment]
Actually I don't have any **use_frameworks!** in my pod. And I am checking my .**podspec** file, not he **Podfile**.

**Comment by iSevenDays** [comment]
Please provide us full logs so we will be able to investigate this further.

**Comment by itsaboutcode** [comment]
**My PodSpec**

```
#
# Be sure to run `pod lib lint ProjectXYZ.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = "ProjectXYZ"
  s.version          = "0.0.2"
  s.summary          = "This library will be used to do all kind of communication with QuickBlox"

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!  
#  s.description      = <<-DESC
#                       DESC

  s.homepage         = "https://github.com/Teleglobal/ProjectXYZ"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "Muhammad Adil" => “abc@abc.com” }
  s.source           = { :git => "https://github.com/XYZOrganization/ProjectXYZ.git", :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.platform     = :ios, '7.0'
  s.requires_arc = true

#s.vendored_frameworks   = "QuickBlox/QuickBlox.framework"

  s.ios.frameworks      = "MobileCoreServices", "SystemConfiguration", "AVFoundation", "CoreVideo", "Accelerate", "CoreMedia", "AudioToolbox", "CoreLocation", "CoreData", "CoreGraphics", "CFNetwork", "UIKit", "GLKit", "VideoToolbox"
  s.libraries           = "icucore","resolv", "xml2", "c++", "z"

  s.prefix_header_contents =
'#import <Quickblox/Quickblox.h>
#import <CoreData/CoreData.h>
#import <Quickblox/QBMulticastDelegate.h>
#import <Bolts/Bolts.h>'

  s.source_files = 'Pod/Classes/**/*'
  s.resource_bundles = {
    'ProjectXYZ' => ['Pod/Assets/*.png']
  }

  s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  s.dependency 'QMServices', '0.3.6'
  s.dependency 'Quickblox-WebRTC', '2.1.1'
  s.dependency 'SSKeychain', '1.2.3'
  s.dependency 'Reachability', '3.2'
  s.dependency 'SVProgressHUD', '1.1.3'
end

```

**ERROR**

```
$ pod lib lint --verbose

    ProjectXYZ (0.0.2) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `ProjectXYZ` from `/Users/abcuser/ProjectXYZ`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A Bolts
  A ProjectXYZ
  A QMServices
  A QuickBlox
  A Quickblox-WebRTC
  A Reachability
  A SSKeychain
  A SVProgressHUD

Downloading dependencies

-> Installing Bolts (1.5.0)
  > Copying Bolts from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/Bolts/1.5.0-722ab` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/Bolts`

-> Installing ProjectXYZ (0.0.2)

-> Installing QMServices (0.3.6)
  > Copying QMServices from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/QMServices/0.3.6-76fe1` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/QMServices`

-> Installing QuickBlox (2.6.5)
  > Copying QuickBlox from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/QuickBlox/2.6.5-9aaad` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/QuickBlox`

-> Installing Quickblox-WebRTC (2.1.1)
  > Copying Quickblox-WebRTC from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/Quickblox-WebRTC/2.1.1-e0ce2` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/Quickblox-WebRTC`

-> Installing Reachability (3.2)
  > Copying Reachability from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/Reachability/3.2-33e18` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/Reachability`

-> Installing SSKeychain (1.2.3)
  > Copying SSKeychain from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/SSKeychain/1.2.3-3f429` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/SSKeychain`

-> Installing SVProgressHUD (1.1.3)
  > Copying SVProgressHUD from `/Users/abcuser/Library/Caches/CocoaPods/Pods/Release/SVProgressHUD/1.1.3-74808` to
  `../../../private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/SVProgressHUD`
  - Running pre install hooks
 -> ProjectXYZ (0.0.2)
    - WARN  | url: The URL (https://github.com/XYZOrganization/ProjectXYZ) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/QuickBlox/Quickblox.framework and /private/var/folders/xn/wmk4hb1930q_xms_zt70rr2m0000gn/T/CocoaPods/Lint/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework)) during validation.

[!] ProjectXYZ did not pass validation, due to 1 error and 1 warning.
You can use the `--no-clean` option to inspect any issue.

/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:181:in `block in run'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `each'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `run'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/abcuser/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `load'
/Users/abcuser/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/abcuser/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Raikerian** [comment]
Currently there is no way to do it, as "QMServices" will require "Quickblox", and  "Quickblox" can't be compiled as a library for now:
https://github.com/QuickBlox/q-municate-services-ios/issues/119
https://github.com/QuickBlox/q-municate-services-ios/issues/111
https://github.com/QuickBlox/q-municate-services-ios/issues/98

If you are still having any troubles please let us know by creating a separate issue :)
